#!/bin/sh
############################################################
# Select the specified bluetooth device as pulseaudio sink #
# If it isn't connected, select the analog output        #
############################################################

MAC_ADDRESS=$1
ANALOG_OUT="analog-stereo"

device_index() {
  device=$1
  index="$(pacmd list-sinks | \
    grep -B1 name:.*$device | \
    grep -Eo '[[:digit:]]+' | head -n1)"
  echo $index
}

device_connected() {
  # is the device connected via bluetooth
  device=$1
  bluetoothctl info $device | grep "Connected: yes"
}

device_selected() {
  # is the device selected as default sink in pulseaudio
  device=$1
  pactl info | grep "Default Sink:.*$device"
}

headphone_plugged_in() {
  # is there something plugged into the analog out
  grep -A4 -ri 'Headphone Playback Switch' /proc/asound/card*/* | \
    grep "Amp-Out vals:.*0x00 0x00"
}

while true; do
  if [[ ! $(device_selected $ANALOG_OUT) ]] && \
  ([[ $(headphone_plugged_in) ]] || \
  [[ ! $(device_connected $MAC_ADDRESS) ]]); then
    # select analog output if cable plugged in or device not connected
    pacmd set-default-sink $(device_index $ANALOG_OUT)
    if [[ $(device_selected $ANALOG_OUT) ]]; then
      echo "Analogue audio out set as default by bluetooth-audio" | \
        systemd-cat -p info
    fi
  elif [[ $(device_connected $MAC_ADDRESS) ]] && \
  [[ ! $(device_selected ${MAC_ADDRESS//:/_}) ]] && \
  [[ ! $(headphone_plugged_in) ]]; then
    # select bluetooth device when connection detected
    pacmd set-default-sink $(device_index ${MAC_ADDRESS//:/_})
    if [[ $(device_selected ${MAC_ADDRESS//:/_}) ]]; then
      echo "speaker $MAC_ADDRESS set as default by bluetooth-audio" | \
        systemd-cat -p info
    fi
  fi
  sleep 1
done
